### ISSUE TITLE
readings

### ISSUE THREAD

**Issue by ginfung** [ai-se/privacy_sharing#1]
- [x] Fayola TSE13-LACE
- [x] Fayola ICSE15-LACE2

**Comment by ginfung** [comment]
In LACE2 section IV-C, there is a term named "relevancy filtering", as well as "noise filtering". Can anyone explain them briefly? @timm @rahlk @vivekaxl

**Comment by Ginfung** [comment]
Close

**Comment by Ginfung** [comment]
Close

**Comment by vivekaxl** [comment]
I have not read this paper :(
