### ISSUE TITLE
lace1 & lace2 results

### ISSUE THREAD

**Issue by ginfung** [ai-se/privacy_sharing#11]
```
DEFAULT = {
    'model': ['camel-1.6', 'xerces-1.4', 'ant-1.7'],
    'test_set_ratio': 0.2,
    'CLIFF_percentage': 20,
    'Lace2_holder_number': 5,
    'MORPH_alpha': 0.15,
    'MORPH_beta': 0.35,
}
```

![screen shot 2016-03-04 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/3222148/13540992/b50535ec-e227-11e5-8d9e-d9e126b9615d.png)

![screen shot 2016-03-04 at 4 42 57 pm](https://cloud.githubusercontent.com/assets/3222148/13541071/2fea9acc-e228-11e5-995a-1644f8840767.png)

**Comment by ginfung** [comment]
Both Lace1 and Lace2 outperforms the original data.
Lace2 performs no worse than the Lace1

All of the measures in the tables are "higher is better"

**Comment by ginfung** [comment]
@timm  any comments? We might need to try larger datasets.

**Comment by timm** [comment]
:+1:

**Comment by timm** [comment]
fyi- increased pf is **bad** (higher false alarm rate)

but that is not the issue here. 

the real win is that we have a reproduced result
