### ISSUE TITLE
college record

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/privacy_sharing#12]
## dependent variables
- retention rate
- revenues.
- completion
- earnings
- less chort default rate.

**Comment by timm** [comment]
lets see 5 plots for the above, numbers in sorted order

**Comment by ginfung** [comment]
RET_FT4 (retention rate full time 4 year)
![image](https://cloud.githubusercontent.com/assets/3222148/18256082/8c9138e8-737e-11e6-81d0-de56e8c5130b.png)

**Comment by ginfung** [comment]
TUITFTE (tuition)
![image](https://cloud.githubusercontent.com/assets/3222148/18256178/e4433568-737f-11e6-8646-73a26312c92c.png)

**Comment by ginfung** [comment]
AVGFACSAL (average faculty salary per month)
![image](https://cloud.githubusercontent.com/assets/3222148/18256257/d54cc5fa-7380-11e6-9ed3-73c7322d86a0.png)

**Comment by ginfung** [comment]
CDR3 (three-year default cohort default rate)
Cohort default rates are produced annually as an institutional accountability metric; schools with too-high default rates may lose access to federal financial aid.

![image](https://cloud.githubusercontent.com/assets/3222148/18256540/a4f5173c-7384-11e6-91a6-0bd73491c146.png)

**Comment by Ginfung** [comment]
r lets see 5 plots for the above, numbers in sorted order
 - we can see that most metrics are with high spread.
-  unfortunately, there is no earning data available in the table (at least in yr2013)

**Comment by ginfung** [comment]
> lets see 5 plots for the above, numbers in sorted order
- we can see that most metrics are with high spread.
-  unfortunately, there is no earning data available in the table (at least in yr2013)

**Comment by ginfung** [comment]
C150_4 (rate of 4year full times student complete within 150% of the expected time)
![image](https://cloud.githubusercontent.com/assets/3222148/18256620/d1084208-7385-11e6-9941-c9f9a7d6b4a2.png)

**Comment by ginfung** [comment]
TODO
- [x] pick up the independent and dependent attributes
- [ ] remove the invalid rows

**Comment by ginfung** [comment]
dataset considered from https://collegescorecard.ed.gov/downloads/Most-Recent-Cohorts-All-Data-Elements.csv

attributes considered in this experiment:
INSTNM
CONTROL
ADM_RATE
SAT_AVG
TUITFTE
RET_FT4
AVGFACSAL [removed]
PCTFLOAN
PCTPELL
DEBT_MDN
C150_4
CDR3

dependent variable:
mn_earn_wne_p

**Comment by timm** [comment]
all but AVGFACSAL (average faculty salary per month) look like valid targets for learning in this domain
