### ISSUE TITLE
collegecard::IPR and association rule

### ISSUE THREAD

**Issue by ginfung** [ai-se/privacy_sharing#16]
![ipr](https://cloud.githubusercontent.com/assets/3222148/18639383/b0183472-7e61-11e6-84bf-4597341f38b7.png)

**Comment by ginfung** [comment]
| DATE | CLOCK | MODEL | HANDELER | ORG(item#) | PTZ(item#) | ORG(rule#) | PTZ(rule#) | preserve rate | reveal rate |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 91916 | 1474301404 | school | Lace2Out | 90 | 78 | 2 | 0 | 0 | 0 |
| 91916 | 1474301406 | school | Lace1Out | 91 | 95 | 2 | 8 | 1 | 0.25 |
| 91916 | 1474301406 | school | Lace2Out | 94 | 85 | 2 | 0 | 0 | 0 |
| 91916 | 1474301408 | school | Lace1Out | 92 | 96 | 11 | 23 | 0.545 | 0.261 |
| 91916 | 1474301409 | school | Lace2Out | 90 | 86 | 3 | 0 | 0 | 0 |
| 91916 | 1474301411 | school | Lace1Out | 88 | 91 | 2 | 6 | 1 | 0.333 |
| 91916 | 1474301411 | school | Lace2Out | 93 | 96 | 2 | 13 | 0 | 0 |
| 91916 | 1474301413 | school | Lace1Out | 91 | 95 | 11 | 21 | 0.455 | 0.238 |
| 91916 | 1474301414 | school | Lace2Out | 88 | 90 | 3 | 4 | 0.667 | 0.5 |
| 91916 | 1474301416 | school | Lace1Out | 92 | 93 | 3 | 8 | 0.667 | 0.25 |
| 91916 | 1474301416 | school | Lace2Out | 91 | 88 | 0 | 3 | 0 | 0 |
| 91916 | 1474301418 | school | Lace1Out | 90 | 91 | 3 | 6 | 0.667 | 0.333 |
| 91916 | 1474301419 | school | Lace2Out | 90 | 92 | 0 | 0 | 0 | 0 |
| 91916 | 1474301421 | school | Lace1Out | 88 | 94 | 0 | 20 | 0 | 0 |
| 91916 | 1474301421 | school | Lace2Out | 92 | 91 | 12 | 5 | 0.167 | 0.4 |
| 91916 | 1474301423 | school | Lace1Out | 88 | 94 | 6 | 8 | 0.333 | 0.25 |
| 91916 | 1474301424 | school | Lace2Out | 89 | 86 | 2 | 4 | 0 | 0 |
| 91916 | 1474301426 | school | Lace1Out | 93 | 98 | 7 | 7 | 0 | 0 |
| 91916 | 1474301426 | school | Lace2Out | 91 | 84 | 10 | 2 | 0 | 0 |
| 91916 | 1474301428 | school | Lace1Out | 92 | 93 | 4 | 7 | 0 | 0 |
| 91916 | 1474301429 | school | Lace2Out | 91 | 98 | 3 | 9 | 0 | 0 |
| 91916 | 1474301431 | school | Lace1Out | 84 | 90 | 0 | 12 | 0 | 0 |
| 91916 | 1474301431 | school | Lace2Out | 92 | 89 | 2 | 3 | 0 | 0 |
| 91916 | 1474301433 | school | Lace1Out | 91 | 99 | 4 | 18 | 0.75 | 0.167 |
| 91916 | 1474301434 | school | Lace2Out | 89 | 90 | 4 | 4 | 0.75 | 0.75 |
| 91916 | 1474301436 | school | Lace1Out | 91 | 88 | 0 | 10 | 0 | 0 |
| 91916 | 1474301437 | school | Lace2Out | 99 | 86 | 6 | 1 | 0.167 | 1 |
| 91916 | 1474301438 | school | Lace1Out | 89 | 83 | 4 | 9 | 0.5 | 0.222 |
| 91916 | 1474301439 | school | Lace2Out | 94 | 94 | 3 | 5 | 0 | 0 |
| 91916 | 1474301441 | school | Lace1Out | 94 | 86 | 2 | 3 | 0 | 0 |
| 91916 | 1474301441 | school | Lace2Out | 91 | 98 | 4 | 9 | 1 | 0.444 |
| 91916 | 1474301443 | school | Lace1Out | 94 | 93 | 11 | 7 | 0.273 | 0.429 |
| 91916 | 1474301444 | school | Lace2Out | 89 | 91 | 0 | 0 | 0 | 0 |
| 91916 | 1474301446 | school | Lace1Out | 94 | 92 | 12 | 7 | 0.167 | 0.286 |
| 91916 | 1474301447 | school | Lace2Out | 90 | 88 | 1 | 10 | 1 | 0.1 |
| 91916 | 1474301448 | school | Lace1Out | 89 | 93 | 0 | 6 | 0 | 0 |
| 91916 | 1474301449 | school | Lace2Out | 87 | 101 | 2 | 4 | 0 | 0 |
| 91916 | 1474301451 | school | Lace1Out | 100 | 92 | 4 | 3 | 0 | 0 |
| 91916 | 1474301452 | school | Lace2Out | 96 | 94 | 6 | 2 | 0 | 0 |

**Comment by timm** [comment]
cant quite understand... 

```
DATE    CLOCK   MODEL   : 
```

these i get

```
HHANDELER   : lace1,2 . ok. these i get these
```

dont get the following

```
ORG(item#)  PTZ(item#)  ORG(rule#)  PTZ(rule#)  
preserve rate   reveal rate
```

what is an example of a pair of rules with  low/high preserve/reveal rates

**Comment by ginfung** [comment]
the first figure-- IPR was defined at  Fayola's paper. It shows that both lace1 and lace2 has high IPR. what's more, LACE2 outperforms LACE1.

**Comment by ginfung** [comment]
The second table. 
DATE, CLOCK were the experiment time. ignore that. MODEL is the schoolcard study case.

This table try to prove that the association rule did not preserve after the LACE1(2) algorithm

ORG(rule#) is the number of association rules found in the original data set
PTZ(rule#) is the association rules found in the output of LACE1(2) algorithm.

preserve rate = how many association rules in the ORG were preserved  in the LACE1(2) output
reveal rate = how many association rules in the LACE1(2) output were actually existed in the original dataset.

From this table, we can see that the number of association rules were very small (compared to ant models).

the association rules are disappeared  after LACE1/2. 

same conclusions as https://github.com/ai-se/privacy_sharing/issues/10

**Comment by timm** [comment]
thank you. so we can say "privitization for a purpose" works.

**Comment by ginfung** [comment]
> thank you. so we can say "privitization for a purpose" works.

yep.

**Comment by ginfung** [comment]
This is an experiments for "privatization for a purpose"
This supports "privatization for a purpose"
but not so very good as we might expect

![lr](https://cloud.githubusercontent.com/assets/3222148/18657022/548c152a-7ec4-11e6-9b79-75271235d007.png)
![dt](https://cloud.githubusercontent.com/assets/3222148/18657024/5665948e-7ec4-11e6-8698-924a9917f8c5.png)

**Comment by ginfung** [comment]
Correlation matrix in original data set
![org_data_coor](https://cloud.githubusercontent.com/assets/3222148/18858529/add916d4-843a-11e6-965e-96e1c3452569.png)

Correlation matrix in Lace2 results
![org_lace2_coor](https://cloud.githubusercontent.com/assets/3222148/18858538/bcb8ad2c-843a-11e6-9ba6-96aae1aad94a.png)
