### ISSUE TITLE
Morphing w/ Starminer Installed

### ISSUE THREAD

**Issue by TheButterKing** [ai-se/privacy_sharing#6]
Basically, I morph it crashes. I looked all over the internet and never found a compatibility fixing. If you know how or IChun can make version 1.9.3 for 1.7.10 with compatibility let me know

**Comment by ginfung** [comment]
@TheButterKing can't understand what you mean. Would you give me more details?

**Comment by TheButterKing** [comment]
I found out that the reason why my morph mod crashes when i morph is combatibility issues wit starminer, so I was hoping that someone could find out why and how to fix it.
